FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm ci --only=production

FROM node:22-alpine

WORKDIR /app
RUN apk add --no-cache curl
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001

COPY --from=builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --chown=nodejs:nodejs ./src/. ./src
COPY --chown=nodejs:nodejs package*.json ./

USER nodejs
EXPOSE 3002

ENV NODE_ENV=production
ENV PORT=3002

HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=3 \
  CMD curl -f http://0.0.0.0:3002/health || exit 1

CMD ["node", "src/index.js"]
